# Use Makefiles in yahoo_cfg_dev package
ROOT=/home/y
include $(ROOT)/share/yahoo_cfg/Make.defs
 
SUBDIRS=common/ phpext/
 
include $(ROOT)/share/yahoo_cfg/Make.rules
 
# Do not place any rules or targets above this line
